ThaDafinser/ZfcDatagrid

src/ZfcDatagrid/Datagrid.php

correct missing or incorrect doctype
for "setToolbarTemplate" should be "string"?

doctype correct

---

view/zfc-datagrid/renderer/bootstrapTable/footer.phtml

When click the table row trigger a checkbox click

Click Table Row

---

src/ZfcDatagrid/Column/Formatter/HtmlTag.php
src/ZfcDatagrid/Column/Formatter/Link.php
src/ZfcDatagrid/Column/Style/Color.php
src/ZfcDatagrid/Column/Type/Image.php
src/ZfcDatagrid/DataSource/Doctrine2/Paginator.php
src/ZfcDatagrid/Renderer/AbstractExport.php
src/ZfcDatagrid/Renderer/Csv/Renderer.php
src/ZfcDatagrid/Renderer/PHPExcel/Renderer.php
src/ZfcDatagrid/Renderer/TCPDF/Renderer.php
tests/ZfcDatagridTest/DataSource/Doctrine2/Mocks/EntityManagerMock.php

Hi,
fixed Formatter\Link
little doc blocks added
private changed to protected in Formatter\HtmlTag property attributes

BuildError

---

view/zfc-datagrid/renderer/jqGrid/footer.phtml

the footer is on the window tablet on 2 lines

Support for Tablet

---

src/ZfcDatagrid/Renderer/TCPDF/Renderer.php

remove tcpdf default image

---

src/ZfcDatagrid/Renderer/AbstractRenderer.php

This should allow export without user action (cache)

export without cache

---

composer.json
docs/03. Columns.md
src/ZfcDatagrid/Column/AbstractColumn.php
src/ZfcDatagrid/Column/Action.php
src/ZfcDatagrid/Column/Formatter/GenerateLink.php
src/ZfcDatagrid/Column/Style/AbstractColor.php
src/ZfcDatagrid/Column/Style/Align.php
src/ZfcDatagrid/Column/Type/PhpArray.php
src/ZfcDatagrid/Datagrid.php
src/ZfcDatagrid/PrepareData.php
src/ZfcDatagrid/Renderer/BootstrapTable/View/Helper/TableRow.php
src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php
tests/ZfcDatagridTest/Column/AbstractColumnTest.php
tests/ZfcDatagridTest/PrepareDataTest.php

Kokspflanze multiple formatter

---

autoload_classmap.php
docs/03. Columns.md
src/ZfcDatagrid/Column/Action/AbstractAction.php
tests/ZfcDatagridTest/Column/Action/AbstractActionTest.php

Add the possibility to use another column's value to make the comparison.

Show Action based on columns value

---

src/ZfcDatagrid/Column/Action/AbstractAction.php
src/ZfcDatagrid/PrepareData.php
tests/ZfcDatagridTest/Column/Action/AbstractActionTest.php

@shinesoftware pls try this fix
https://github.com/ThaDafinser/ZfcDatagrid/pull/203

fixing toArray #191 #203

---

src/ZfcDatagrid/Filter.php
tests/ZfcDatagridTest/FilterTest.php

Do not change the user input filter

fixing #116 / user search text

---

config/module.config.php
config/zfcdatagrid.local.php.dist
src/ZfcDatagrid/Renderer/AbstractRenderer.php
src/ZfcDatagrid/Renderer/BootstrapTable/Renderer.php
src/ZfcDatagrid/Renderer/JqGrid/Renderer.php
view/zfc-datagrid/renderer/bootstrapTable/layout.phtml
view/zfc-datagrid/renderer/jqGrid/layout.phtml
view/zfc-datagrid/toolbar/export.phtml

Allow GET instead of POST

---

view/zfc-datagrid/renderer/bootstrapTable/layout.phtml

Compare a dropdown's filter active value to the raw key value from the array

---

view/zfc-datagrid/renderer/bootstrapTable/layout.phtml

Hi,
- added table-responsive in bootstrapTable/layout, for big tables on mobile views
- convert old array notation to []
thanks=)

added table-responsive

---

view/zfc-datagrid/renderer/bootstrapTable/layout.phtml

- in `ZfcDatagrid\Filter` line 97 we use a string casted value, so i think we have to cast the value for the selected check too
- some codestyles changes
- some class fixxes in layout.phtml=)
Thanks =)

improvement filter_select

---

src/ZfcDatagrid/Renderer/PHPExcel/Renderer.php

fix type hint class from PHPExcel_Worksheet to \PHPExcel_Worksheet

fix type hint class

---

src/ZfcDatagrid/Renderer/Csv/Renderer.php
src/ZfcDatagrid/Renderer/PHPExcel/Renderer.php

refer to this issue : CSV file don't care about charset=utf-8 header #223

Fix utf8 decode for Excel

---

src/ZfcDatagrid/Renderer/AbstractRenderer.php
src/ZfcDatagrid/Renderer/Csv/Renderer.php
src/ZfcDatagrid/Renderer/JqGrid/Renderer.php
src/ZfcDatagrid/Renderer/PHPExcel/Renderer.php
src/ZfcDatagrid/Renderer/TCPDF/Renderer.php
src/ZfcDatagrid/Renderer/ZendTable/Renderer.php
tests/ZfcDatagridTest/Renderer/AbstractRendererTest.php

hi,
to https://github.com/ThaDafinser/ZfcDatagrid/pull/159
I have changed the translation handling in the different renderer, so the translator would not be required.
Thanks=)

translator required

---

composer.json
src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php
tests/ZfcDatagridTest/Renderer/JqGrid/View/Helper/ColumnsTest.php

Hi,
bugfix for https://github.com/ThaDafinser/ZfcDatagrid/issues/220
also translator fix @jqGrid

Bugfix for style-align @ jqGrid

---

src/ZfcDatagrid/Filter.php
src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php
tests/ZfcDatagridTest/FilterTest.php
tests/ZfcDatagridTest/Renderer/JqGrid/View/Helper/ColumnsTest.php

also run php-cs-fixer
fix for https://github.com/ThaDafinser/ZfcDatagrid/issues/155

bugfix for Type\Number filter with comma

---

src/ZfcDatagrid/Renderer/BootstrapTable/View/Helper/TableRowFactory.php
src/ZfcDatagrid/Renderer/JqGrid/View/Helper/ColumnsFactory.php

hi,
added getServiceLocator in both view-helper, we get there a `Zend\ServiceManager\AbstractPluginManager` object so we have to use this method.

view helper AbstractPluginManager

---

.travis.yml
composer.json

dropped PHP 5.5

---

config/module.config.php
src/ZfcDatagrid/Column/Action.php
src/ZfcDatagrid/Renderer/TCPDF/Renderer.php

Adds two new options for customizing the row height calculation in PDF renderer.

PDF options for row height paddings

---

.travis.yml

added PHP 7.1 in travis for tests

PHP 7.1 in travis

---

README.md
docs/01. Introduction.md
docs/02. Quick Start.md

- changed array syntax in docs
- update ZendFramework link
- updated PHP 5.6+ in requirements

little doc-update

---

composer.json
src/ZfcDatagrid/Renderer/TCPDF/Renderer.php

added phpoffice/phpexcel and tecnickcom/tcpdfin require-dev
fixxed case-sensitive error in `ZfcDatagrid\Renderer\TCPDF`

phpoffice/phpexcel and tecnickcom/tcpdfin in composer.json

---

composer.json

i think its good part for testing 1.4 and 2.0, if we add this in the composer.json

added extra-tag in composer.json

---

composer.json
src/ZfcDatagrid/Renderer/PHPExcel/Renderer.php
src/ZfcDatagrid/Renderer/TCPDF/Renderer.php

Merge remote-tracking branch 'remotes/upstream/master' into develop_master_merge
#	composer.json
#	src/ZfcDatagrid/Renderer/TCPDF/Renderer.php
develop_master_merge

Develop master merge

---

src/ZfcDatagrid/DataSource/PhpArray.php

Provide case insensitive natural sort for strings.

Case insensitive natural sort for strings

---

.travis.yml
composer.json

added php 7.2 in travis
also moved hhvm to `allow_failures` section

added php 7.2 in travis
